
  name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # Updated to a supported Ruby version
          bundler-cache: true

      - name: Fix executable permissions
        run: chmod +x bin/*

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # Updated to a supported Ruby version
          bundler-cache: true

      - name: Fix executable permissions
        run: chmod +x bin/*

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # Updated to a supported Ruby version
          bundler-cache: true

      - name: Fix executable permissions
        run: chmod +x bin/*

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y \
          google-chrome-stable \
          curl \
          libjemalloc2 \
          libvips \
          sqlite3 \
          libsqlite3-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # Updated to a supported Ruby version
          bundler-cache: true

      - name: Fix executable permissions
        run: chmod +x bin/*

      - name: Prepare test database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
